export const INCOMING_ORDERS = 'APP/INCOMING_ORDERS';
export const REQUEST_ORDERS = 'APP/REQUEST_ORDERS';
export const FILTER_ORDERS_BY = 'APP/FILTER_ORDERS_BY';
export const REMOVE_FILTER = 'APP/REMOVE_FILTER';
export const RESET_FILTERS = 'APP/RESET_FILTERS';